version: "3.8"

services:
  app01:
    build: .
    ports:
      - "5000:5000"
    networks:
      -  unifast-network
    depends_on:
      - db01

  db01:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "myBANKadmin#y4p3"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - unifast-network
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
    external: true
  
networks:
  unifast-network:
    driver: bridge